// this is a boiler plate code generated by copilot we just update accordingly
import httpClient from "./http";
import type { AxiosResponse } from "axios";
import type {
  ApiResponse,
  LoginRequest,
  LoginResponse,
  RefreshTokenRequest,
  RefreshTokenResponse,
  User,
} from "./types";
import { API_ENDPOINTS } from "./apiEndpoints";
class AuthService {
  /**
   * Login user with email and password
   */
  async login(credentials: LoginRequest): Promise<LoginResponse> {
    try {
      // Create URLSearchParams for form-encoded data
      const formData = new URLSearchParams();
      formData.append("username", credentials.username);
      formData.append("password", credentials.password);
      formData.append("grant_type", "password");

      const response: AxiosResponse<ApiResponse<LoginResponse>> =
        await httpClient.post(API_ENDPOINTS.auth.login, formData, {
          headers: {
            "Content-Type": "application/x-www-form-urlencoded",
          },
        });

      console.log("Login response:", response);

      // Handle response - OAuth2 server might return different format
      const responseData: any = response.data.data || response.data;

      if (responseData.token && responseData.refresh_token) {
        localStorage.setItem("authToken", responseData.token);
        localStorage.setItem("refreshToken", responseData.refresh_token);

        // Fetch user profile after successful login
        try {
          await this.fetchUserProfile();
        } catch (profileError) {
          console.error(
            "[AuthService] Failed to fetch user profile after login:",
            profileError
          );
          // Don't throw here, login was successful even if profile fetch failed
        }
      }
      return responseData;
    } catch (error) {
      console.error("[AuthService] Login failed:", error);
      throw error;
    }
  }

  /**
   * Logout user and clear all auth data
   */
  async logout(): Promise<void> {
    try {
      // Call logout endpoint to invalidate tokens on server
      await httpClient.post(API_ENDPOINTS.auth.logout);
    } catch (error) {
      console.error("[AuthService] Logout API call failed:", error);
      // Continue with local cleanup even if API call fails
    } finally {
      // Clear all auth data
      this.clearAuthData();
    }
  }

  /**
   * Refresh access token using refresh token
   */
  async refreshToken(): Promise<RefreshTokenResponse> {
    try {
      const refreshToken =
        localStorage.getItem("refreshToken") ||
        sessionStorage.getItem("refreshToken");

      if (!refreshToken) {
        throw new Error("No refresh token available");
      }

      const response: AxiosResponse<ApiResponse<RefreshTokenResponse>> =
        await httpClient.post("/auth/refresh", {
          refreshToken,
        } as RefreshTokenRequest);

      const { data } = response.data;

      // Update stored tokens (maintain storage preference)
      if (localStorage.getItem("authToken")) {
        localStorage.setItem("authToken", data.accessToken);
        localStorage.setItem("refreshToken", data.refreshToken);
      } else {
        sessionStorage.setItem("authToken", data.accessToken);
        sessionStorage.setItem("refreshToken", data.refreshToken);
      }

      return data;
    } catch (error) {
      console.error("[AuthService] Token refresh failed:", error);
      // Clear auth data if refresh fails
      this.clearAuthData();
      throw error;
    }
  }

  /**
   * Fetch user profile from API
   */
  async fetchUserProfile(): Promise<User> {
    try {
      const response: AxiosResponse<ApiResponse<User>> = await httpClient.post(
        API_ENDPOINTS.auth.user
      );

      const userData = response.data.data;

      // Store user data in localStorage
      localStorage.setItem("user", JSON.stringify(userData));

      return userData;
    } catch (error) {
      console.error("[AuthService] Failed to fetch user profile:", error);
      throw error;
    }
  }

  /**
   * Get current user from stored data
   */
  getCurrentUser(): User | null {
    try {
      const userData = localStorage.getItem("user");
      return userData ? JSON.parse(userData) : null;
    } catch (error) {
      console.error("[AuthService] Failed to parse user data:", error);
      return null;
    }
  }

  /**
   * Check if user is authenticated
   */
  isAuthenticated(): boolean {
    const token =
      localStorage.getItem("authToken") || sessionStorage.getItem("authToken");
    const user = this.getCurrentUser();
    return !!(token && user);
  }

  /**
   * Get current auth token
   */
  getAuthToken(): string | null {
    return (
      localStorage.getItem("authToken") || sessionStorage.getItem("authToken")
    );
  }

  /**
   * Clear all authentication data
   */
  private clearAuthData(): void {
    // Clear tokens
    localStorage.removeItem("authToken");
    localStorage.removeItem("refreshToken");
    sessionStorage.removeItem("authToken");
    sessionStorage.removeItem("refreshToken");

    // Clear user data
    localStorage.removeItem("user");

    // Dispatch logout event for app-wide state management
    window.dispatchEvent(new CustomEvent("auth:logout"));
  }

  /**
   * Register new user
   */
  async register(userData: {
    email: string;
    password: string;
    firstName: string;
    lastName: string;
  }): Promise<LoginResponse> {
    try {
      const response: AxiosResponse<ApiResponse<LoginResponse>> =
        await httpClient.post("/auth/register", userData);

      const { data } = response.data;

      // Store tokens in session storage by default for new registrations
      // sessionStorage.setItem("authToken", data.accessToken);
      // sessionStorage.setItem("refreshToken", data.refreshToken);
      // localStorage.setItem("user", JSON.stringify(data.user));

      return data;
    } catch (error) {
      console.error("[AuthService] Registration failed:", error);
      throw error;
    }
  }

  /**
   * Request password reset
   */
  async requestPasswordReset(email: string): Promise<void> {
    try {
      await httpClient.post("/auth/forgot-password", { email });
    } catch (error) {
      console.error("[AuthService] Password reset request failed:", error);
      throw error;
    }
  }

  /**
   * Reset password with token
   */
  async resetPassword(token: string, newPassword: string): Promise<void> {
    try {
      await httpClient.post("/auth/reset-password", {
        token,
        password: newPassword,
      });
    } catch (error) {
      console.error("[AuthService] Password reset failed:", error);
      throw error;
    }
  }

  /**
   * Verify email with token
   */
  async verifyEmail(token: string): Promise<void> {
    try {
      await httpClient.post("/auth/verify-email", { token });
    } catch (error) {
      console.error("[AuthService] Email verification failed:", error);
      throw error;
    }
  }

  /**
   * Resend email verification
   */
  async resendEmailVerification(): Promise<void> {
    try {
      await httpClient.post("/auth/resend-verification");
    } catch (error) {
      console.error("[AuthService] Resend verification failed:", error);
      throw error;
    }
  }
}

// Create and export singleton instance
const authService = new AuthService();
export default authService;
