// this is a boiler plate code generated by copilot we just update accordingly
import httpClient from "./http";
import type { AxiosResponse } from "axios";
import type {
  ApiResponse,
  PaginatedResponse,
  UserProfile,
  UpdateUserRequest,
  User,
  SearchRequest,
  FamilyMember,
  BusinessProfile,
} from "./types";

class UserService {
  /**
   * Get current user profile
   */
  async getUserProfile(): Promise<UserProfile> {
    try {
      const response: AxiosResponse<ApiResponse<UserProfile>> =
        await httpClient.get("/user/profile");
      return response.data.data;
    } catch (error) {
      console.error("[UserService] Failed to get user profile:", error);
      throw error;
    }
  }

  /**
   * Update current user profile
   */
  async updateUserProfile(userData: UpdateUserRequest): Promise<UserProfile> {
    try {
      const response: AxiosResponse<ApiResponse<UserProfile>> =
        await httpClient.put("/user/profile", userData);

      // Update stored user data
      const updatedUser = response.data.data;
      localStorage.setItem("user", JSON.stringify(updatedUser));

      return updatedUser;
    } catch (error) {
      console.error("[UserService] Failed to update user profile:", error);
      throw error;
    }
  }

  /**
   * Get user by ID
   */
  async getUserById(id: string): Promise<UserProfile> {
    try {
      const response: AxiosResponse<ApiResponse<UserProfile>> =
        await httpClient.get(`/user/${id}`);
      return response.data.data;
    } catch (error) {
      console.error("[UserService] Failed to get user by ID:", error);
      throw error;
    }
  }

  /**
   * Search users
   */
  async searchUsers(
    searchParams: SearchRequest,
  ): Promise<PaginatedResponse<User>> {
    try {
      const response: AxiosResponse<PaginatedResponse<User>> =
        await httpClient.get("/user/search", {
          params: searchParams,
        });
      return response.data;
    } catch (error) {
      console.error("[UserService] Failed to search users:", error);
      throw error;
    }
  }

  /**
   * Upload user avatar
   */
  async uploadAvatar(file: File): Promise<{ avatarUrl: string }> {
    try {
      const formData = new FormData();
      formData.append("avatar", file);

      const response: AxiosResponse<ApiResponse<{ avatarUrl: string }>> =
        await httpClient.post("/user/avatar", formData, {
          headers: {
            "Content-Type": "multipart/form-data",
          },
        });

      return response.data.data;
    } catch (error) {
      console.error("[UserService] Failed to upload avatar:", error);
      throw error;
    }
  }

  /**
   * Delete user avatar
   */
  async deleteAvatar(): Promise<void> {
    try {
      await httpClient.delete("/user/avatar");
    } catch (error) {
      console.error("[UserService] Failed to delete avatar:", error);
      throw error;
    }
  }

  /**
   * Change user password
   */
  async changePassword(
    currentPassword: string,
    newPassword: string,
  ): Promise<void> {
    try {
      await httpClient.post("/user/change-password", {
        currentPassword,
        newPassword,
      });
    } catch (error) {
      console.error("[UserService] Failed to change password:", error);
      throw error;
    }
  }

  /**
   * Delete user account
   */
  async deleteAccount(): Promise<void> {
    try {
      await httpClient.delete("/user/account");

      // Clear all stored data after account deletion
      localStorage.clear();
      sessionStorage.clear();
    } catch (error) {
      console.error("[UserService] Failed to delete account:", error);
      throw error;
    }
  }

  /**
   * Get user's family tree data
   */
  async getUserFamilyMembers(): Promise<FamilyMember[]> {
    try {
      const response: AxiosResponse<ApiResponse<FamilyMember[]>> =
        await httpClient.get("/user/family");
      return response.data.data;
    } catch (error) {
      console.error("[UserService] Failed to get family members:", error);
      throw error;
    }
  }

  /**
   * Add family member
   */
  async addFamilyMember(
    memberData: Omit<FamilyMember, "id">,
  ): Promise<FamilyMember> {
    try {
      const response: AxiosResponse<ApiResponse<FamilyMember>> =
        await httpClient.post("/user/family", memberData);
      return response.data.data;
    } catch (error) {
      console.error("[UserService] Failed to add family member:", error);
      throw error;
    }
  }

  /**
   * Update family member
   */
  async updateFamilyMember(
    id: string,
    memberData: Partial<FamilyMember>,
  ): Promise<FamilyMember> {
    try {
      const response: AxiosResponse<ApiResponse<FamilyMember>> =
        await httpClient.put(`/user/family/${id}`, memberData);
      return response.data.data;
    } catch (error) {
      console.error("[UserService] Failed to update family member:", error);
      throw error;
    }
  }

  /**
   * Delete family member
   */
  async deleteFamilyMember(id: string): Promise<void> {
    try {
      await httpClient.delete(`/user/family/${id}`);
    } catch (error) {
      console.error("[UserService] Failed to delete family member:", error);
      throw error;
    }
  }

  /**
   * Get user's business profiles
   */
  async getUserBusinesses(): Promise<BusinessProfile[]> {
    try {
      const response: AxiosResponse<ApiResponse<BusinessProfile[]>> =
        await httpClient.get("/user/businesses");
      return response.data.data;
    } catch (error) {
      console.error("[UserService] Failed to get user businesses:", error);
      throw error;
    }
  }

  /**
   * Get user preferences
   */
  async getUserPreferences(): Promise<UserProfile["preferences"]> {
    try {
      const response: AxiosResponse<ApiResponse<UserProfile["preferences"]>> =
        await httpClient.get("/user/preferences");
      return response.data.data;
    } catch (error) {
      console.error("[UserService] Failed to get user preferences:", error);
      throw error;
    }
  }

  /**
   * Update user preferences
   */
  async updateUserPreferences(
    preferences: Partial<UserProfile["preferences"]>,
  ): Promise<UserProfile["preferences"]> {
    try {
      const response: AxiosResponse<ApiResponse<UserProfile["preferences"]>> =
        await httpClient.put("/user/preferences", preferences);
      return response.data.data;
    } catch (error) {
      console.error("[UserService] Failed to update user preferences:", error);
      throw error;
    }
  }
}

// Create and export singleton instance
const userService = new UserService();
export default userService;
